[package]
name = "timelord-cli"
version = "3.0.0"
edition = "2024"

[[bin]]
name = "timelord"
path = "src/main.rs"

[dependencies]
timelord = { path = "../timelord" }
camino = { version = "1.1.9", features = ["serde1"] }
clap = { version = "4.5.32", features = ["derive"] }
env_logger = "0.11.7"
